CREATE TABLE EK_MODIFIER_INTERP
  (
    DECLARING_CONCEPT VARCHAR2(50) NOT NULL,
    C_BASECODE        VARCHAR2(50) NOT NULL,
    PROPERTYNAME      VARCHAR2(255) NOT NULL,
    DISPLAYNAME       VARCHAR2(255)
  );
