--------------------------------------------------------
--  File created - Wednesday-April-22-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table EUREKAPHENOTYPEONTOLOGY
--------------------------------------------------------

  CREATE TABLE "EUREKAPHENOTYPEONTOLOGY" 
   (	"C_HLEVEL" NUMBER(22,0), 
	"C_FULLNAME" VARCHAR2(700), 
	"C_NAME" VARCHAR2(2000), 
	"C_SYNONYM_CD" CHAR(1), 
	"C_VISUALATTRIBUTES" CHAR(3), 
	"C_TOTALNUM" NUMBER(22,0), 
	"C_BASECODE" VARCHAR2(50), 
	"C_METADATAXML" CLOB, 
	"C_FACTTABLECOLUMN" VARCHAR2(50), 
	"C_TABLENAME" VARCHAR2(50), 
	"C_COLUMNNAME" VARCHAR2(50), 
	"C_COLUMNDATATYPE" VARCHAR2(50), 
	"C_OPERATOR" VARCHAR2(10), 
	"C_DIMCODE" VARCHAR2(700), 
	"C_COMMENT" CLOB, 
	"C_TOOLTIP" VARCHAR2(900), 
	"M_APPLIED_PATH" VARCHAR2(700), 
	"UPDATE_DATE" DATE, 
	"DOWNLOAD_DATE" DATE, 
	"IMPORT_DATE" DATE, 
	"SOURCESYSTEM_CD" VARCHAR2(50), 
	"VALUETYPE_CD" VARCHAR2(50), 
	"M_EXCLUSION_CD" VARCHAR2(25), 
	"C_PATH" VARCHAR2(700), 
	"C_SYMBOL" VARCHAR2(50), 
	"EK_UNIQUE_ID" VARCHAR2(50)
   ) ;
--------------------------------------------------------
--  DDL for Index META_APPLIED_PATH_EKPHE_IDX
--------------------------------------------------------

  CREATE INDEX "META_APPLIED_PATH_EKPHE_IDX" ON "EUREKAPHENOTYPEONTOLOGY" ("M_APPLIED_PATH") 
  ;
--------------------------------------------------------
--  DDL for Index META_FULLNAME_EKPHE_IDX
--------------------------------------------------------

  CREATE INDEX "META_FULLNAME_EKPHE_IDX" ON "EUREKAPHENOTYPEONTOLOGY" ("C_FULLNAME") 
  ;
--------------------------------------------------------
--  DDL for Index META_SYMBOL_EKPHE_IDX
--------------------------------------------------------

  CREATE INDEX "META_SYMBOL_EKPHE_IDX" ON "EUREKAPHENOTYPEONTOLOGY" ("C_SYMBOL") 
  ;
--------------------------------------------------------
--  Constraints for Table EUREKAPHENOTYPEONTOLOGY
--------------------------------------------------------

  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_HLEVEL" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_FULLNAME" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_NAME" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_SYNONYM_CD" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_VISUALATTRIBUTES" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_FACTTABLECOLUMN" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_TABLENAME" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_COLUMNNAME" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_COLUMNDATATYPE" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_OPERATOR" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "C_DIMCODE" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "M_APPLIED_PATH" SET NOT NULL;
  ALTER TABLE "EUREKAPHENOTYPEONTOLOGY" ALTER COLUMN "UPDATE_DATE" SET NOT NULL;
