--------------------------------------------------------
-- DDL FOR TEMPORARY TABLES FOR H2
--------------------------------------------------------

CREATE LOCAL TEMPORARY TABLE IF NOT EXISTS EK_TEMP_UNIQUE_IDS (UNIQUE_ID VARCHAR2(700)) ON COMMIT DELETE ROWS;
CREATE LOCAL TEMPORARY TABLE IF NOT EXISTS EK_TEMP_PROPERTIES
   (	EK_UNIQUE_ID VARCHAR2(50), 
	M_APPLIED_PATH VARCHAR2(700), 
        DECLARING_CONCEPT_ID VARCHAR2(50),
	C_NAME VARCHAR2(2000), 
	VALUETYPE_CD VARCHAR2(50), 
	PROPERTYNAME VARCHAR2(255), 
	C_METADATAXML CLOB
   ) ON COMMIT DELETE ROWS;
